--------------------------------------------------------
--  Fichier créé - mardi-novembre-01-2022   
--------------------------------------------------------
DROP TABLE "SYSTEM"."PAIMENT";
DROP TABLE "SYSTEM"."ADMIN";
DROP TABLE "SYSTEM"."CLIENT";
DROP TABLE "SYSTEM"."EMPLOYEE";
DROP TABLE "SYSTEM"."OFFICE";
DROP TABLE "SYSTEM"."EVENT";
--------------------------------------------------------
--  DDL for Table PAIMENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PAIMENT" 
   (	"NUM_FACT" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(255 BYTE), 
	"TYPEE" VARCHAR2(50 BYTE), 
	"PRICE" NUMBER(*,0), 
	"ID_OFFICE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADMIN" 
   (	"USER_ID" NUMBER(*,0), 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"PHONE_NUMBER" NUMBER(*,0), 
	"EMAIL" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CLIENT" 
   (	"ID_CLIENT" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(255 BYTE), 
	"EMAIL_ADRESSE" VARCHAR2(50 BYTE), 
	"PHONE_NUMBER" NUMBER(*,0), 
	"AGE" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLOYEE" 
   (	"ID_EMPLOYEE" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(255 BYTE), 
	"TYPEE" VARCHAR2(50 BYTE), 
	"ROLEE" VARCHAR2(50 BYTE), 
	"PHONE_NUMBER" NUMBER(*,0), 
	"DATEE" DATE, 
	"ID_OFFICE" NUMBER, 
	"ID_EVENT" NUMBER(*,0), 
	"NUM_FACT" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OFFICE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."OFFICE" 
   (	"ID_OFFICE" NUMBER(*,0), 
	"NAME_OFFICE" VARCHAR2(50 BYTE), 
	"DESCRIPTION_OFFICE" VARCHAR2(50 BYTE), 
	"PRICE_OFFICE" NUMBER(*,0), 
	"IMAGE_OFFICE" VARCHAR2(255 BYTE), 
	"POSITION_OFFICE" VARCHAR2(255 BYTE), 
	"SPACE_OFFICE" NUMBER(*,0), 
	"TYPE_OFFICE" VARCHAR2(255 BYTE), 
	"STATUS_OFFICE" VARCHAR2(255 BYTE), 
	"DATE_OFFICE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EVENT" 
   (	"ID_EVENT" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(255 BYTE), 
	"TYPEE" VARCHAR2(50 BYTE), 
	"DATEE" DATE, 
	"ID_OFFICE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.PAIMENT
SET DEFINE OFF;
REM INSERTING into SYSTEM.ADMIN
SET DEFINE OFF;
Insert into SYSTEM.ADMIN (USER_ID,USER_NAME,PASSWORD,PHONE_NUMBER,EMAIL) values ('39','mahmoud','abid','26371661','mahoud.abid@esprit.tn');
REM INSERTING into SYSTEM.CLIENT
SET DEFINE OFF;
REM INSERTING into SYSTEM.EMPLOYEE
SET DEFINE OFF;
REM INSERTING into SYSTEM.OFFICE
SET DEFINE OFF;
Insert into SYSTEM.OFFICE (ID_OFFICE,NAME_OFFICE,DESCRIPTION_OFFICE,PRICE_OFFICE,IMAGE_OFFICE,POSITION_OFFICE,SPACE_OFFICE,TYPE_OFFICE,STATUS_OFFICE,DATE_OFFICE) values ('70','i''m a god',null,null,'C:/Users/Mon Pc/Desktop/Qt projects/BrainStormSpace/img/office.png',null,'10',null,null,null);
Insert into SYSTEM.OFFICE (ID_OFFICE,NAME_OFFICE,DESCRIPTION_OFFICE,PRICE_OFFICE,IMAGE_OFFICE,POSITION_OFFICE,SPACE_OFFICE,TYPE_OFFICE,STATUS_OFFICE,DATE_OFFICE) values ('69','i''m not a man',null,null,'C:/Users/Mon Pc/Desktop/Qt projects/BrainStormSpace/img/office.png',null,'5',null,null,null);
Insert into SYSTEM.OFFICE (ID_OFFICE,NAME_OFFICE,DESCRIPTION_OFFICE,PRICE_OFFICE,IMAGE_OFFICE,POSITION_OFFICE,SPACE_OFFICE,TYPE_OFFICE,STATUS_OFFICE,DATE_OFFICE) values ('80','Mahmoud','good','1200','C:/Users/Mon Pc/Desktop/Qt projects/BrainStormSpace/img/office.png','north','700',null,null,'11/25/2020');
Insert into SYSTEM.OFFICE (ID_OFFICE,NAME_OFFICE,DESCRIPTION_OFFICE,PRICE_OFFICE,IMAGE_OFFICE,POSITION_OFFICE,SPACE_OFFICE,TYPE_OFFICE,STATUS_OFFICE,DATE_OFFICE) values ('74','Wicked','office in Lac1 with air conditioner','800','C:/Users/Mon Pc/Desktop/Qt projects/BrainStormSpace/img/office.png','north','600',null,null,'12/25/2020');
Insert into SYSTEM.OFFICE (ID_OFFICE,NAME_OFFICE,DESCRIPTION_OFFICE,PRICE_OFFICE,IMAGE_OFFICE,POSITION_OFFICE,SPACE_OFFICE,TYPE_OFFICE,STATUS_OFFICE,DATE_OFFICE) values ('86',null,null,null,'C:/Users/Mon Pc/Desktop/Qt projects/BrainStormSpace/img/office.png',null,null,'office','available',null);
Insert into SYSTEM.OFFICE (ID_OFFICE,NAME_OFFICE,DESCRIPTION_OFFICE,PRICE_OFFICE,IMAGE_OFFICE,POSITION_OFFICE,SPACE_OFFICE,TYPE_OFFICE,STATUS_OFFICE,DATE_OFFICE) values ('79','Mahmoud','good','1200','C:/Users/Mon Pc/Desktop/Qt projects/BrainStormSpace/img/office.png','north','700',null,null,'11/25/2020');
Insert into SYSTEM.OFFICE (ID_OFFICE,NAME_OFFICE,DESCRIPTION_OFFICE,PRICE_OFFICE,IMAGE_OFFICE,POSITION_OFFICE,SPACE_OFFICE,TYPE_OFFICE,STATUS_OFFICE,DATE_OFFICE) values ('81','GoodChechen','if you want to call me tap 26371661','1200','C:/Users/Mon Pc/Desktop/Qt projects/BrainStormSpace/img/office.png','north','700',null,null,'11/25/2020');
Insert into SYSTEM.OFFICE (ID_OFFICE,NAME_OFFICE,DESCRIPTION_OFFICE,PRICE_OFFICE,IMAGE_OFFICE,POSITION_OFFICE,SPACE_OFFICE,TYPE_OFFICE,STATUS_OFFICE,DATE_OFFICE) values ('83','GoodChechen','if you want to call me tap 26371661','1200','C:/Users/Mon Pc/Desktop/Qt projects/BrainStormSpace/img/office.png','north','700',null,'available','11/25/2020');
Insert into SYSTEM.OFFICE (ID_OFFICE,NAME_OFFICE,DESCRIPTION_OFFICE,PRICE_OFFICE,IMAGE_OFFICE,POSITION_OFFICE,SPACE_OFFICE,TYPE_OFFICE,STATUS_OFFICE,DATE_OFFICE) values ('85','oumayma','zeazeazrzf','25000','C:/Users/Mon Pc/Desktop/Qt projects/BrainStormSpace/img/office.png','west','15987','office','available','02/05/2022');
--------------------------------------------------------
--  DDL for Index SYS_C004117
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C004117" ON "SYSTEM"."PAIMENT" ("NUM_FACT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C004034
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C004034" ON "SYSTEM"."ADMIN" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C004115
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C004115" ON "SYSTEM"."CLIENT" ("ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C004123
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C004123" ON "SYSTEM"."EMPLOYEE" ("ID_EMPLOYEE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C004046
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C004046" ON "SYSTEM"."OFFICE" ("ID_OFFICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PAIMENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PAIMENT" MODIFY ("NUM_FACT" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PAIMENT" ADD PRIMARY KEY ("NUM_FACT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADMIN" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."ADMIN" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."ADMIN" MODIFY ("USER_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."ADMIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."ADMIN" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."ADMIN" MODIFY ("EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CLIENT" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENT" ADD PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYEE" MODIFY ("ID_EMPLOYEE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE" ADD PRIMARY KEY ("ID_EMPLOYEE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OFFICE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."OFFICE" MODIFY ("ID_OFFICE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."OFFICE" ADD PRIMARY KEY ("ID_OFFICE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAIMENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PAIMENT" ADD CONSTRAINT "FK_OFFICE" FOREIGN KEY ("ID_OFFICE")
	  REFERENCES "SYSTEM"."OFFICE" ("ID_OFFICE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYEE" ADD CONSTRAINT "FK_EMPLOYEE" FOREIGN KEY ("ID_OFFICE")
	  REFERENCES "SYSTEM"."OFFICE" ("ID_OFFICE") ENABLE;
 
  ALTER TABLE "SYSTEM"."EMPLOYEE" ADD CONSTRAINT "FK_EMPLOYEE1" FOREIGN KEY ("ID_EVENT")
	  REFERENCES "SYSTEM"."EVENT" ("ID_EVENT") ENABLE;
 
  ALTER TABLE "SYSTEM"."EMPLOYEE" ADD CONSTRAINT "FK_EMPLOYEE2" FOREIGN KEY ("NUM_FACT")
	  REFERENCES "SYSTEM"."PAIMENT" ("NUM_FACT") ENABLE;
